swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module Transaction
      summary: Get user transactions
      description: API for fetching all user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          required: true
          description: ID of the account to get
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User Module Transaction
      summary: Add new transaction on user account
      description: Add a new transaction to user account
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          required: true
          description: ID of the account to post
        - name: body
          in: body
          description: transaction payload
          required: true
          schema:
            $ref: '#/definitions/Transactions_Post'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction's infos updated successfully
          schema:
            $ref: '#/definitions/Transactions_Post_Response'
        '400':
          description: token is required.
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module Transaction
      summary: Get a specific user transaction
      description: API for fetching one user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          required: true
          description: Account ID to get
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction to get
      produces:
        - application/json
      responses:
        '200':
          description: User Transaction retrieved successully
          schema:
            $ref: '#/definitions/Transaction_Details'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}/details:
    put:
      security:
        - Bearer: []
      tags:
        - User Module Transaction
      summary: Update a specific user transaction
      description: API for updating a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          required: true
          description: Account ID to edit
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction to edit
        - in: body
          name: body
          description: Update user transaction
          required: true
          schema:
            $ref: '#/definitions/Transactions_Post'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/Transactions_Post_Response'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module Transaction
      summary: Update a specific user transaction
      description: API for updating a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          required: true
          description: Account ID to edit
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction to edit
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            type: object
            properties:
              message: 
                type: string
                example: Transaction details deleted successfully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transactions retrieved succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction_Details'
  Transactions_Post:
    type: object
    properties:
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: note user want to add
  Transactions_Post_Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transaction updated succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction_Details'
  Transaction_Details:
    type: object
    properties:
      transactionId:
        type: string
        description: transaction unique id
      date:
        type: string
        description: transaction date
      type:
        type: string
        description: transaction type
      amount:
        type: number
        description: transaction amount
      message:
        type: string
        description: transaction category
      details:
        type: object
        properties:
          category:
            type: string
            description: transaction category
          notes:
            type: string
            description: note user want to add
  